=== jaxsb/jaxsb/sample/src/main/resources/id.xsd
<!--
  Copyright (c) 2006 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->
<xs:schema elementFormDefault="qualified"
  targetNamespace="http://cf.safris.org/xsb/sample/id.xsd"
  xmlns:id="http://cf.safris.org/xsb/sample/id.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:complexType name="authorType">
    <xs:all>
      <xs:element name="name" type="xs:string"/>
    </xs:all>
    <xs:attribute name="id" type="xs:ID" use="required"/>
  </xs:complexType>

  <xs:complexType name="bookType">
    <xs:sequence>
      <xs:element name="isbn-10" type="xs:anyURI"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="author" type="xs:IDREF"/>
      <xs:element name="co-authors" type="xs:IDREFS" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="directoryType">
    <xs:sequence>
      <xs:element name="author" type="id:authorType" maxOccurs="unbounded"/>
      <xs:element name="book" type="id:bookType" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="directory" type="id:directoryType"/>
  
</xs:schema>

=== jaxsb/jaxsb/sample/src/main/resources/xml/id.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2006 Seva Safris
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<id:directory
  xmlns:id="http://xml.safris.org/toolkit/sample/binding/id.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/toolkit/sample/binding/id.xsd ../xsd/id.xsd">
  <id:author id="bgreene">
    <id:name>Brian Greene</id:name>
  </id:author>
  <id:author id="shawking">
    <id:name>Stephen Hawking</id:name>
  </id:author>
  <id:author id="kthorne">
    <id:name>Kip S. Thorne</id:name>
  </id:author>
  <id:author id="inovikov">
    <id:name>Igor Novikov</id:name>
  </id:author>
  <id:author id="tferris">
    <id:name>Timothy Ferris</id:name>
  </id:author>
  <id:author id="alightman">
    <id:name>Alan Lightman</id:name>
  </id:author>
  <id:author id="rprice">
    <id:name>Richard H. Price</id:name>
  </id:author>
  <id:author id="lmlodinow">
    <id:name>Leonard Mlodinow</id:name>
  </id:author>
  <id:book>
    <id:isbn-10>0393058581</id:isbn-10>
    <id:title>The Elegant Universe</id:title>
    <id:author>bgreene</id:author>
  </id:book>
  <id:book>
    <id:isbn-10>039332446X</id:isbn-10>
    <id:title>The Future of Spacetime</id:title>
    <id:author>shawking</id:author>
    <id:co-authors>kthorne inovikov tferris alightman rprice</id:co-authors>
  </id:book>
  <id:book>
    <id:isbn-10>0553380168</id:isbn-10>
    <id:title>A Briefer History of Time</id:title>
    <id:author>shawking</id:author>
    <id:co-authors>lmlodinow</id:co-authors>
  </id:book>
</id:directory>
