=== jaxsb/jaxsb/sample/src/main/resources/substitutionGroup.xsd
<!--
  Copyright (c) 2006 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->
<xs:schema elementFormDefault="qualified"
  targetNamespace="http://xsb.safris.org/sample/substitutionGroup.xsd"
  xmlns:sg="http://xsb.safris.org/sample/substitutionGroup.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  
  <xs:element name="stockList">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sg:product" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="product" type="sg:productType" abstract="true"/>
  
  <xs:complexType name="productType">
    <xs:sequence>
      <xs:element name="amount" type="xs:positiveInteger"/>
      <xs:element name="name" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="shirt" substitutionGroup="sg:product">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="sg:productType">
          <xs:sequence>
            <xs:element name="size" type="sg:shirtSizeType"/>
            <xs:element name="color" type="sg:colorType"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="hat" substitutionGroup="sg:product">
    <xs:complexType>
      <xs:complexContent>
        <xs:extension base="sg:productType">
          <xs:sequence>
            <xs:element name="size" type="sg:hatSizeType"/>
          </xs:sequence>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>
  </xs:element>
  
  <xs:element name="umbrella" substitutionGroup="sg:product"/>

  <xs:simpleType name="shirtSizeType">
    <xs:restriction base="xs:nonNegativeInteger">
      <xs:enumeration value="0"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="6"/>
      <xs:enumeration value="8"/>
      <xs:enumeration value="10"/>
      <xs:enumeration value="12"/>
      <xs:enumeration value="14"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="hatSizeType">
    <xs:restriction base="xs:Name">
      <xs:enumeration value="S"/>
      <xs:enumeration value="M"/>
      <xs:enumeration value="L"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="colorType">
    <xs:restriction base="xs:Name">
      <xs:enumeration value="BLACK"/>
      <xs:enumeration value="WHITE"/>
      <xs:enumeration value="BLUE"/>
      <xs:enumeration value="RED"/>
    </xs:restriction>
  </xs:simpleType>
  
</xs:schema>

=== jaxsb/jaxsb/sample/src/main/resources/xml/substitutionGroup.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2006 Seva Safris
  
  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:
  
  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.
  
  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<stockList
  xmlns="http://xml.safris.org/toolkit/sample/binding/substitutionGroup.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/toolkit/sample/binding/substitutionGroup.xsd ../xsd/substitutionGroup.xsd">
  <shirt>
    <amount>352</amount>
    <name>Short-Sleeved Linen Blouse</name>
    <size>10</size>
    <color>BLUE</color>
  </shirt>
  <shirt>
    <amount>123</amount>
    <name>Short-Sleeved Silk Blouse</name>
    <size>8</size>
    <color>WHITE</color>
  </shirt>
  <hat>
    <amount>76</amount>
    <name>Ten-Gallon Hat</name>
    <size>L</size>
  </hat>
  <hat>
    <amount>223</amount>
    <name>Wool Beanie Hat</name>
    <size>M</size>
  </hat>
  <umbrella>
    <amount>445</amount>
    <name>Deluxe Golf Umbrella</name>
  </umbrella>
  <umbrella>
    <amount>119</amount>
    <name>Rainbow-Brella</name>
  </umbrella>
</stockList>
