=== jaxsb/jaxsb/test/src/test/resources/xsd/unit/name.xsd
<!--
  Copyright (c) 2008 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<xs:schema elementFormDefault="qualified"
  targetNamespace="http://xml.safris.org/schema/binding/test/unit/name.xsd"
  xmlns:na="http://xml.safris.org/schema/binding/test/unit/name.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="name">
    <xs:sequence>
      <xs:element ref="na:name"/>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:NCName"/>
    <xs:attribute ref="na:Name"/>
    <xs:attribute name="name" type="xs:NCName"/>
    <xs:attribute ref="na:name"/>
  </xs:complexType>
  
  <xs:complexType name="Name">
    <xs:complexContent>
      <xs:extension base="na:name">
        <xs:sequence>
          <xs:element ref="na:name"/>
          <xs:element name="name" type="na:name" minOccurs="0"/>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:notation name="name" public="name"/>
  
  <xs:notation name="Name" public="Name"/>
  
  <xs:attribute name="name" type="xs:boolean"/>
  
  <xs:attribute name="Name" type="xs:boolean"/>
  
  <xs:element name="name" type="na:name" nillable="true"/>

  <xs:element name="Name" type="na:Name" nillable="true"/>
  
  <xs:element name="root">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="na:name" maxOccurs="unbounded"/>
        <xs:element ref="na:Name" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== jaxsb/jaxsb/test/src/test/resources/xml/unit/name.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright (c) 2008 Seva Safris

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You should have received a copy of The MIT License (MIT) along with this
  program. If not, see <http://opensource.org/licenses/MIT/>.
-->

<na:root
  xmlns:na="http://xml.safris.org/schema/binding/test/unit/name.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://xml.safris.org/schema/binding/test/unit/name.xsd ../../xsd/unit/name.xsd">
  <na:name>
    <na:name na:Name="false" na:name="true">
      <na:name>
        <na:name na:Name="true" na:name="false">
          <na:name>
            <na:name
              xsi:nil="true" name="stuff" Name="more"/>
          </na:name>
        </na:name>
      </na:name>
    </na:name>
  </na:name>
  <na:name na:Name="false" na:name="true">
    <na:name>
      <na:name na:Name="true" na:name="false" name="what" Name="when">
        <na:name
          xsi:nil="true"/>
      </na:name>
    </na:name>
  </na:name>
  <na:name>
    <na:name na:Name="false" na:name="true" name="where" Name="here">
      <na:name
        xsi:nil="true"/>
    </na:name>
  </na:name>
  <na:Name na:Name="true" na:name="false" name="hi" Name="hello" xsi:nil="false">
    <na:name>
      <na:name na:Name="false" na:name="true">
        <na:name>
          <na:name
            xsi:nil="true" name="nill" Name="yup"/>
        </na:name>
      </na:name>
    </na:name>
    <na:name>
      <na:name
        xsi:nil="true" name="who" Name="ever" na:Name="true" na:name="false"/>
    </na:name>
  </na:Name>
  <na:Name name="really" Name="yup" na:Name="true" na:name="true">
    <na:name>
      <na:name name="my" Name="world" na:Name="true" na:name="true">
        <na:name
          xsi:nil="true"/>
      </na:name>
    </na:name>
    <na:name
      xsi:nil="true"/>
  </na:Name>
</na:root>
